### ISSUE TITLE
Bug: Atlas Texture

### ISSUE THREAD

**Issue by nancikennedy** [kemayo/wow-handynotes-longforgottenhippogryph#1]
On Retail, with latest (the alpha) version installed, this happens when logging in/reloading:

Message: .../AddOns/HandyNotes_LongForgottenHippogryph/nodes.lua:16: attempt to call field 'atlas_texture' (a nil value)
Time: Sat Nov 19 19:40:22 2022
Count: 1
Stack: .../AddOns/HandyNotes_LongForgottenHippogryph/nodes.lua:16: attempt to call field 'atlas_texture' (a nil value)
[string "@Interface/AddOns/HandyNotes_LongForgottenHippogryph/nodes.lua"]:16: in main chunk

Locals: myname = "HandyNotes_LongForgottenHippogryph"
ns = <table> {
 defaultsOverride = <table> {
 }
 hiddenConfig = <table> {
 }
}
(*temporary) = <table> {
 note = "Use five of these before anyone else, without leaving the zone or dying, and you'll get the {item:138258:Reins of the Long-Forgotten Hippogryph}"
 label = "Ephemeral Crystal"
}
(*temporary) = nil
(*temporary) = "islands-azeritechest"
(*temporary) = <table> {
 b = 0.500000
 g = 0
 r = 1
}
(*temporary) = "attempt to call field 'atlas_texture' (a nil value)"

**Comment by kemayo** [comment]
Same build issue as the other project you commented on. Same fix, really. Again, thanks!
