### ISSUE TITLE
Bug: Can't open handler.xml

### ISSUE THREAD

**Issue by nancikennedy** [kemayo/wow-handynotes-longforgottenhippogryph#2]
On Retail, with latest (alpha) installed:

Message: Interface\FrameXML\Bindings.xml:16 Couldn't open Interface/AddOns/HandyNotes_LongForgottenHippogryph/handler/handler.xml
Time: Sat Nov 19 19:43:27 2022
Count: 1

**Comment by nancikennedy** [comment]
Also getting:

Message: Interface\FrameXML\Bindings.xml:1 Interface\FrameXML\Bindings.xml:16 Couldn't open Interface/AddOns/HandyNotes_LongForgottenHippogryph/handler/handler.xml
Time: Sat Nov 19 19:43:27 2022
Count: 1

**Comment by nancikennedy** [comment]
Also getting:

Message: Interface\FrameXML\Bindings.xml:1 Interface\FrameXML\Bindings.xml:16 Couldn't open Interface/AddOns/HandyNotes_LongForgottenHippogryph/handler/handler.xml
Time: Sat Nov 19 19:43:27 2022
Count: 1

**Comment by nancikennedy** [comment]
These happen when logging in/reloading

**Comment by kemayo** [comment]
Should all be fixed in the new release
